### ISSUE TITLE
UI adjustments

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/dip-access-interface#119]

**Comment by bunekcca** [comment]
We'd need to make some adjustments:
-When characters typed in a searchbox and press enter, launch the search
-On the homepage only keep the searchbox which is in the body of the page, get rid of the one in the header (but keep it on the other pages)
![image](https://user-images.githubusercontent.com/38663513/52427563-3017b380-2ace-11e9-8c0d-7ef1d81ed208.png)
-Search results page: replace the column heading "View parent folder" by "Collection Name"
![image](https://user-images.githubusercontent.com/38663513/52427705-779e3f80-2ace-11e9-843d-971ac34fb99d.png)
-Search results page: replace Size (bytes) by Readable size
![image](https://user-images.githubusercontent.com/38663513/52427817-b59b6380-2ace-11e9-9108-b0fcc99a8185.png)
-File detail page: display the file name (if possible)
![image](https://user-images.githubusercontent.com/38663513/52428387-d3b59380-2acf-11e9-8bb0-2777c23fd25f.png)
-Breadcrumb: replace the current datas displayed by more intelligible ones (collection name, folder name, filename if possible
![image](https://user-images.githubusercontent.com/38663513/52428485-0c556d00-2ad0-11e9-83fc-988d9f3e7815.png)
-File detail page: take out UUID, Pronom ID, METS amdSEC and checksum fields from the page
![image](https://user-images.githubusercontent.com/38663513/52428645-648c6f00-2ad0-11e9-809d-66def3727853.png)

**Comment by jraddaoui** [comment]
Hi @sallain, this is ready for an initial review in the test instance if you want to give it a try before passing it to Bun and Stefana.

First of all, here is no related pull request for this work yet and it's deployed from a development branch to include the work for #91 and this one.

Second, a few notes about the requested changes:

1 - Hitting enter in the search box already launched the search (and the input value was added to the main input in the search page). It should also be the same from the main input in the homepage and the new one alongside the digital files filters.
2 - The search-box is now removed in the homepage and also in the search page, where it does the same as the input in the digital files filters.
3 - If I understood correctly, you want the "View parent folder" column removed from the search page. Otherwise, let me know and I'll add it back.
4 - Breadcrumbs will look a little funky in small window widths when log titles are used for collections and folders.

**Comment by stefanabreitwieser** [comment]
@bunekcca Would you mind testing this one, since it's primarily UI? If it looks good, you can close the ticket. Thanks!!

**Comment by bunekcca** [comment]
Hi @jraddaoui,
That's perfect.
Thanks a lot.
