### ISSUE TITLE
Formatting issues for Dublin Core fields in collections

### ISSUE THREAD

**Issue by stefanabreitwieser** [CCA-Public/dip-access-interface#132]
Hi all, 

Just adding a new collection to the test instance, and I noticed two issues: 

1. Line breaks do not appear in the "Description" or "Format" fields.
2. The language field is limited to a small amount of characters. It's typical for collections to have three or more languages at CCA (a very international collection!), so the limit should be much higher or removed.

Are these changes possible? Thanks!

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, this is ready for review in the test instance.

1. I had two options for this. One adds paragraph elements to all text blocks, the other uses `<br>` for the line breaks. With the first one you can't have content beside the field label and with the second one is the other way around (mostly because the field value is trimmed by default before it's added to the database) and, for example in a list, the first element is displayed in the label line. This is actually a problem because the same code is used to render all Dublin Core fields. So far I've implemented the second option but, if you want to spend a little more time, we could try to implement a two columns layout for the field labels and values or something like that.

2. I've increased the language field length from 20  to 200 chars.

Best regards.

**Comment by stefanabreitwieser** [comment]
Looks good, thanks Radda!!
