### ISSUE TITLE
Add collection link to digital files table in search page

### ISSUE THREAD

**Issue by jraddaoui** [CCA-Public/dip-access-interface#53]
This will require to add collection data to the digital files search index and to update that data in all digital files descendants of a collection when that collection changes.

**Comment by jraddaoui** [comment]
The biggest deal of this change is the update of all the digital files when the ancestor collection is edited. In Elasticsearch the documents are not related between them, therefore, if a change is made over a collection with 2 descendant folders and 500 descendant digital files, the collection data must be updated in 503 documents.

This can be executed in an efficient way by using partial updates and bulk requests, but it can be a long time process as the application data grows. Ideally, this should be implemented in an asynchronous task after #15 is done.

**Estimate: 16 h**

**Comment by jraddaoui** [comment]
Some notes to test this:

- A link to the ancestor collection should appear in the search page for each file.
- It should show "Untitled" if the collection title is empty.
- The collection title should be searchable in the search page.
- When a collection is edited, if it has descendant files, it should show a notification about a descendants update in progress.
- When a folder is edited, if it has descendant files, it should show a notification too.
- After the async. update finish the correct folder identifier and collection title should be shown in the search page table.

**Comment by sallain** [comment]
@jraddaoui since I'm still pretty new to SCOPE, I'm going to answer each of your points with my testing results just to make sure I'm looking at the right thing.

1. Yes - if I search for "objects/BBhelmet.ai", the search result table has a column called _Collection name_ that contains a link to the collection.
2. Yes - shows Untitled with a link to the collection.
3. Yes - results page shows all digital files belonging to the collection.
4. Yes - a notification pops up reading `A background process has been launched to update the Collection metadata in the Elasticsearch index for the related Digital Files.`
5. Yes - a notification pops up reading `A background process has been launched to update the Folder metadata in the Elasticsearch index for the related Digital Files.`
6. Yes - everything updates properly.

**Comment by stefanabreitwieser** [comment]
@jraddaoui , this looks great!! Going through the same steps: 

1. Yes - same results as Sara. The link is working.
2. No - I updated a collection title to be blank, and searched "*". The old collection name still appears in the search results, still with a working link. (I wasn't able to test from by uploading a new DIP-- we seem to be having issues uploading DIPs from CCA right now.) 
3. Yes - same results as Sara.
4. Yes - same results as Sara.
5. Yes - same results as Sara.
6. Yes, I think? See point 2. 

Let me know if there's anything else you'd like me to test -- thanks so much!

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, it looks like there was another memory issue. More information in https://github.com/CCA-Public/dip-access-interface/issues/127#issuecomment-475027924.

I have restarted the worker, which allowed a couple of import process to finish and the descendants update/delete should work now.

**Comment by stefanabreitwieser** [comment]
Looks great, thanks Radda!
