### ISSUE TITLE
UI: digital file page

### ISSUE THREAD

**Issue by bunekcca** [CCA-Public/dip-access-interface#90]
![image](https://user-images.githubusercontent.com/38663513/44594311-cb70d280-a793-11e8-8eb1-5bdb612db29a.png)
1. Download section is missing, the text here is slightly different
2. Heading for preservation metadata is not correct (should be like Digital file description), the down arrow is missing and the size of the grey rectangle is too wide

**Comment by jraddaoui** [comment]
Hi @bunekcca,

About 1, we never estimated/agreed on doing that, but it shouldn't take a lot of time. I'll do it.

About 2, we gave two different estimates for #62, and the decision was to use the default bootstrap style. Changing that will take 2 extra hours, as noted in that issue.

**Comment by bunekcca** [comment]
Ok thanks for 1, then for 2 we can give it up.

**Comment by stefanabreitwieser** [comment]
Hi @bunekcca and @jraddaoui -- For 1, there shouldn't be a download button on the file page, because you can't download files individually. This is on purpose as we feel strongly that the files should be downloaded on a DIP-level. There's no need to add a button to the file page.

For 2, it seems I misunderstood what the default bootstrap style was -- my bad! I agree with Bun that the look should be consistent. That said, this is a very low priority fix. Let's save it for the end if there's time, or if not, for the next phase.

Thanks to you both!

**Comment by bunekcca** [comment]
Hi @stefanabreitwieser 
Are you sure for #1 ? After the UX testing session, Tim decided to add the download button at the file level, enriched with a text explaining that this is not only the file but a package that will be downloaded. 
![image](https://user-images.githubusercontent.com/38663513/44666086-9d82cc80-a9e5-11e8-9c25-dc856641f66c.png)
I have no strong opinion on that point, but that was a point raised during the usability tests.

**Comment by stefanabreitwieser** [comment]
@bunekcca -- I wasn't involved in the early UX testing, but if it was a point that was raised, then I'm fine with it. @jraddaoui please ignore my last comment and go ahead with Bun's feedback on the first point. (Last UI comment for now I promise!) 

Thank you both!

**Comment by jraddaoui** [comment]
Already added in #100, including the (different) text on each page ;)
