### ISSUE TITLE
Problem: researchers cannot refine or filter search results

### ISSUE THREAD

**Issue by kellyannewithane** [CCA-Public/dip-access-interface#91]
From user stories (round 2, researcher):

-As a Researcher, I want to be able to refine and filter my Search results and to combine multiple refinements (e.g. limit search by file format and date range simultaneously).

-As a Researcher, I want to better understand the context of Folders and refine/filter lists in the Collection and Folder pages by Series (or other) tags.

Parent of #53 
Parent of #54

**Comment by jraddaoui** [comment]
Tags will be added in #20.

**Comment by jraddaoui** [comment]
This is a great point and we could introduce some faceting and/or an advanced search form. A great example is the AtoM browse page for Archival descriptions, but the estimate will vary a lot depending on what should by available to facet and/or filter.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser, I'd need this feature a lot more defined to be able to estimate. Specially:

- What kind of filters (type and filed) should be included and on what pages.
- If the filters options should show a count of resources matching that criteria when it's applied (facets).
- If the filters should allow multiple selection.

**Comment by stefanabreitwieser** [comment]
This is something I'd like to discuss a bit more during the demos (@bunekcca ) but I think filters should be included on the Search results pages and, if possible, on the Folder pages (so that a user can better understand what's in a folder that potentially has thousands of files). 

I'd be interested to hear what Bun has to say about the filters showing a count. I think it would be nice from a UI perspective, but if it's going to be many hours of work, then I don't think it's a high priority for me. 

Yes, the filters should definitely allow for multiple selection. 

Thanks @jraddaoui !

**Comment by jraddaoui** [comment]
Great @stefanabreitwieser,

[Here](https://demo.accesstomemory.org/informationobject/browse?showAdvanced=1&topLod=0) you can see the AtoM browse page with facets (to the left) and other filters in the advanced search form. It doesn't support multiple selection at the moment.

It's worth mention that we could reuse the same filter/facets from the search page in the Folder pages, but it will take more time to define different filters/facets for other models (Collections/Folders).

Having facets (with counts) will take more time than just having a form with filtering options and the same to allow multiple options.

**Comment by bunekcca** [comment]
Hi @jraddaoui and @stefanabreitwieser 

I agree with Stefana, that could be a specific thing we can ask to the testers during the demo. Nevertheless we could already think about what's relevant and have a list that could be modified after the session.
Facets with number could be a great UX feature but it depends on the time we'll spend on it. If we have remaining time at the end, why not.

**Comment by jraddaoui** [comment]
Hi @stefanabreitwieser and @bunekcca,

What filters and in what pages would you like to see in the first iteration of this feature?

**Comment by stefanabreitwieser** [comment]
Hi Radda! 

- filter by format
- filter by version of format (if possible)
- select a range of years (using last modified date)
- filter by parent collection

I also know that we haven't done tagging yet, but we should also expect that we'll want to filter by tag.

@bunekcca is going to follow up with a UX mock-up. Let us know if you have any questions!

**Comment by jraddaoui** [comment]
Thanks @stefanabreitwieser,

That already gives us some things to do while @bunekcca works on the mock-up. We'll need to address #54 for the date range filter and #53 for the collection filter. I'll start with those if that's okay for you.

**Comment by stefanabreitwieser** [comment]
Sounds good -- thanks Radda!

**Comment by bunekcca** [comment]
Hi @jraddaoui, I've just finished the mock ups.
In addition to what Stefana told earlier in the discussion, we could also filter by text. Most importantly we can combine all the filters to narrow down the results.
The prototype is here: https://preview.uxpin.com/3d336639e15f75264bba3ae932b885d057c8f358#/pages/84996202

Here's the base state of the filters:
![image](https://user-images.githubusercontent.com/38663513/52440939-5c8ef800-2aed-11e9-8b3d-dea730ad38d2.png)

For all the filter, you get a search field that filter the list as you type:
![image](https://user-images.githubusercontent.com/38663513/52440997-86481f00-2aed-11e9-90fc-632492573184.png)

To select a value users have to click on "apply"
![image](https://user-images.githubusercontent.com/38663513/52441037-a4158400-2aed-11e9-8b52-ec560903f372.png)

When a value has been selected in a filter, the heading goes bold
![image](https://user-images.githubusercontent.com/38663513/52441075-c3141600-2aed-11e9-807d-4fa1887ce3f7.png)

For the dates; you can either type directly the date using the format indicated or by using the calendar
![image](https://user-images.githubusercontent.com/38663513/52441128-e2ab3e80-2aed-11e9-9815-c9033f9fe194.png)

Using the calendar to select the date, you can browse the year by clicking on the arrow and select the exact date directly in the calendar
![image](https://user-images.githubusercontent.com/38663513/52441239-21d98f80-2aee-11e9-8b76-20581df2a8de.png)
Clicking on OK validates the date.

**Comment by jraddaoui** [comment]
Hi @bunekcca, sorry for the late response.

This is looking amazing, thanks for the detailed mock ups! I think there is no need for a demo or video, but I'd like to make you some questions in here:

1. Should the options showed in the filters be limited to the current results? For example, when no filter is applied, all the formats will appear in that filter but, if a Collection filter is already applied, should the format filter show just the formats inside that Collection or all the formats?

2. Over what digital file metadata works the "Objects types" filter?

3. For the date-pickers, I'd suggest to use a default HTML5 `type="date"` input, which renders a date-picker in most modern browser. Or, if old browser support is required, I'd use the [following widget](https://uxsolutions.github.io/bootstrap-datepicker) that works well with Bootstrap 4. In both cases, clicking the calendar icon will create a new pop-out instead of replacing the drop-down content. Would that be okay for the first iteration of this feature? Creating a custom date-picker to replicate the behavior from the mock ups will require quite some time.

**Comment by bunekcca** [comment]
Hi @jraddaoui 

You'll find my answers below:
#1 Yes it should be dynamic and related to the filters applied.
#2 need to talk about that with @stefanabreitwieser 
#3 what would be difference in terms of working hours between having it like the mock ups and using the default HTML5 one ? If we go with the default HTML5 one, I assume we can change the colors and the font ?

**Comment by jraddaoui** [comment]
Thanks @bunekcca!

3. The difference will be considerable, I can put it in numbers as it will require to analyze how to integrate an existing date-picker to follow that behavior. The default HTML5 date-picker from each browser won't be customizable, but we should be able to do it in the Bootstrap widget plugin.

**Comment by bunekcca** [comment]
We just need to be consistent with the design of the interface, if Bootstrap allows it. Go for it. Opening in a pop up is not a big issue for me.

**Comment by stefanabreitwieser** [comment]
Thanks @bunekcca ! The mock-up looks great. I think "object type" was an example for a type of tag. I think it would be nice to have different categories of tags ("object type" "series name", etc) rather than one tag drop-down (and this should probably be customizable). That said, I don't think this is especially important until we have tagging, but worth keeping in mind. 

Thanks to you both!

**Comment by jraddaoui** [comment]
Hi @sallain, this is ready for an initial review in the test instance if you want to give it a try before passing it to Bun and Stefana.

First of all, the related PR is still in code review and there may still be code changes before it's merged. However, I don't expect huge changes in the behavior of the feature coming from that review.

Second, a few notes about the current implementation:

1 - "Object types" and "Tags" drop-downs are disabled until we implement the tags feature.
2 - If there are no available filters in the "Collections" and "Formats" drop-downs they will also be disabled.
3 - There is no "Apply" button inside the drop-downs as it seems like an unnecessary extra click as the filters are not actually applied until the entire form is sent.
4 - The date-pickers don't have "Cancel" and "OK" buttons, they include a "Clear" button only and the value is added to the input when a date is selected.
5 - The date-pickers should have internationalization support and show-up in French/English when the language is changed. 
6 - The selected filters are not shown over the table. Since multiple selection is allowed and the filters shown in the drop-downs are based on the filters applied, you can deselect one or more directly in the drop-down (which label will be strong to indicate some filters are applied).
7 - The same for the "Reset filters" link. A clear button has been implemented alongside the submit button (which doesn't have the "Apply" label either). I think this looks better and it's more consistent with other search inputs.
8 - On window widths bellow 768 pixels the drop-downs are transformed to behave better in mobile devices (similar to the site header).

**Comment by bunekcca** [comment]
Hi @jraddaoui 

On the french version, the filters are still in english does someone on our end have to translate them ? Where would we have to do that ?

Could you please reduce the width of the text field so it's not so wide. Filters shouldn't take the whole width but only half of the screen:
![image](https://user-images.githubusercontent.com/38663513/54761571-b7c20900-4bc8-11e9-8b2f-810d28a58f2f.png)

Can we also remove the border when a filter is active (we can only keep the blue color on the button to signify the active state):
![image](https://user-images.githubusercontent.com/38663513/54761637-d2947d80-4bc8-11e9-8248-589f1d4a140c.png)

For #6, I think having the filters applied displayed upfront is better UX wise. You see what have been applied upfront. If it's time consuming, could you tell us the required time to make the changes ?

**Comment by jraddaoui** [comment]
Hi @bunekcca, thanks for the feedback!

1. I'm waiting to merge the related PR and the UI adjustments to regenerate the language files and ask you for the translations of the new strings.

2. We can give them a `max-width` for long screen widths, but it won't be exactly 50% in all resolutions. Specially in small resolutions where the responsive design is already implemented.

3. That border is in there for accessibility reasons, it doesn't represent the active status of the drop-down, but the focus status of the button. You may see it's functionality more clearly if you move from the filters with the keyboard. I don't like it either when both status coexist, but removing it may cause unexpected accessibility issues.

4 (previously 6). The main problem with those tags is that they should remove the specified filter by reloading the page with a parameter removed. Since we currently support multiple selection, if you select more than one format for example, you'll see multiple `for` parameters in the URL. Of course, it's not impossible to remove just one of those parameters, but I wanted to know your opinion about the current status before making that part. I think it can be done in between 4 and 8 hours if you think it's necessary.

**Comment by bunekcca** [comment]
Hi @jraddaoui,

OK for 1,2,3.

For #4 I would really prefer to have what has been designed in the mock ups. If you can make it happen that would be great.

**Comment by bunekcca** [comment]
Hi @jraddaoui, 

In terms of planning do you think the changes can be done before Tuesday ? We have our first tests on that day. If it's not possible, I can try to postpone.

Have a good day.

**Comment by jraddaoui** [comment]
Hi @bunekcca,

I'm currently working on this, I hope to have it ready for review by the end of the day or on Monday and, in the worst case, I'll deploy the changes using a dev. branch before Tuesday ;)

Have a good one you too!

**Comment by jraddaoui** [comment]
Hi @bunekcca,

This is ready for review in the test site. It's still pending code review in #135 but I wanted to give you the chance to test it before Tuesday. A couple of notes about it:

1. I've given a `max-width` of 900px to the filters form. The reason not to give it less width is to allow some space for French labels, which may take a little more space than the English ones.

2. I've used [the default badge links](https://getbootstrap.com/docs/4.1/components/badge/#links) from Bootstrap for the filter tags, without any style change. Please, let me know if you really want them with only the blue border and the blue text or any other style change you may want.

**Comment by bunekcca** [comment]
Hi @jraddaoui 

That's perfect!

Thanks a lot.
